### PR TITLE
Fixed invalid indexing of scalar datasets, and updated deprecated datset names

### PR DESCRIPTION
**Pull request by mlouis9**
Updated dataset names to conform to VERA_4.3 naming conventions, and added additional logic to caching/uncaching to account for scalar datasets. The VERA_4.3 output file that these modifications were tested against (VERA progression problem: p9) can be found [here](https://gtvault-my.sharepoint.com/:u:/g/personal/mlouis9_gatech_edu/ER_nEDf9uUpOmF5KJKqKcWUBQPeu0SklZ6ooZcFbTbsUSA?e=eCB3sI).

### CODE REVIEW

**Comment by aarograh** [comment]
Thanks for fixing this @mlouis9 .  For the Kitware developers, I can confirm that the dataset name changes are correct.  VERA used to accept several forms of input for certain datasets; it still accepts various names but always changes them to a standardized form, which is what @mlouis9 has used here.  This is necessary to use VERACore with newer versions of VERA.

For context: I'm the lead developer for VERA at ORNL now (https://www.ornl.gov/staff-profile/aaron-m-graham) and @mlouis9 explored VERACore as part of a summer internship project.

**Comment by patrickoleary** [comment]
Awesome! We'll push these changes forward.

**Comment by lefebvrera** [comment]
@mlouis9 please don't forget to address the coding standard items (`# `, empty line containing whitespace, etc).

**Comment by jourdain** [comment]
The CI is complaining for some formatting. Just run black on the source to fix it

```
black....................................................................Failed
- hook id: black
- exit code: 1

would reformat vera_core/app/core/vera_out_file.py

Oh no! 💥 💔 💥
1 file would be reformatted, 21 files would be left unchanged.

codespell................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

vera_core/app/core/vera_out_file.py:92:1: W293 blank line contains whitespace
vera_core/app/core/vera_out_file.py:93:9: E2[65](https://github.com/Kitware/VERACore/actions/runs/5466149069/jobs/9951156419?pr=3#step:4:66) block comment should start with '# '
```

**Comment by mlouis9** [comment]
That should've fixed the formatting issues. The pre-commit run passes on my end.

**Comment by patrickoleary** [comment]
Great! Is this still work in progress or is good to go? The data set you
sent is great. Can we use it?

**Comment by aarograh** [comment]
I responded by email, but just to close the loop on GitHub where @mlouis9 can see too: yes, no problems with using that updated dataset that @mlouis9 was using.

I'll let @mlouis9 confirm that this is ready to merge.

**Comment by mlouis9** [comment]
Yep, I can confirm; everything is ready.

**Pull request merged**
